
// This file is autogenerated
import * as VERBS from '../verbs'


export interface IInputGit {
  

  

  
}
  
export const InputGit = (basePath : string): IInputGit => {
  return Object.assign(
    
    {
      
    }
  )
}
