
// This file is autogenerated
import * as VERBS from '../verbs'
import {IIssueCommentResponse, IssueCommentResponse} from './IssueCommentResponse'
import {IInputIssueComment, InputIssueComment} from './InputIssueComment'

export interface IInputIssueComments {
  (arg1: number): IInputIssueComment

  

  create(/*args*/) : Promise<IIssueCommentResponse>
fetch(/*args*/) : Promise<IIssueCommentResponse[]>
}
  
export const InputIssueComments = (basePath : string): IInputIssueComments => {
  return Object.assign(
    
(arg1: number) => {
  return InputIssueComment(basePath + '/' + arg1)
},
    
    {
      create(/*args*/) : Promise<IIssueCommentResponse> { return VERBS._create<IIssueCommentResponse>(basePath) },
fetch(/*args*/) : Promise<IIssueCommentResponse[]> { return VERBS._fetch<IIssueCommentResponse[]>(basePath) }
    }
  )
}
