
// This file is autogenerated
import * as VERBS from '../verbs'
import {IIssueCommentResponse, IssueCommentResponse} from './IssueCommentResponse'

export interface IInputIssueComment {
  

  

  fetch(/*args*/) : Promise<IIssueCommentResponse>
update(/*args*/) : Promise<IIssueCommentResponse>
remove(/*args*/) : Promise<void>
}
  
export const InputIssueComment = (basePath : string): IInputIssueComment => {
  return Object.assign(
    
    {
      fetch(/*args*/) : Promise<IIssueCommentResponse> { return VERBS._fetch<IIssueCommentResponse>(basePath) },
update(/*args*/) : Promise<IIssueCommentResponse> { return VERBS._update<IIssueCommentResponse>(basePath) },
remove(/*args*/) : Promise<void> { return VERBS._remove<void>(basePath) }
    }
  )
}
