
// This file is autogenerated
import * as VERBS from '../verbs'
import {IRepoIssueResponse, RepoIssueResponse} from './RepoIssueResponse'
import {IInputRepoIssue, InputRepoIssue} from './InputRepoIssue'

export interface IInputRepoIssues {
  (arg1: number): IInputRepoIssue

  

  create(/*args*/) : Promise<IRepoIssueResponse>
fetch(/*args*/) : Promise<IRepoIssueResponse[]>
}
  
export const InputRepoIssues = (basePath : string): IInputRepoIssues => {
  return Object.assign(
    
(arg1: number) => {
  return InputRepoIssue(basePath + '/' + arg1)
},
    
    {
      create(/*args*/) : Promise<IRepoIssueResponse> { return VERBS._create<IRepoIssueResponse>(basePath) },
fetch(/*args*/) : Promise<IRepoIssueResponse[]> { return VERBS._fetch<IRepoIssueResponse[]>(basePath) }
    }
  )
}
