
// This file is autogenerated
import * as VERBS from '../verbs'
import {IInputRepoIssues, InputRepoIssues} from './InputRepoIssues'
import {IInputGit, InputGit} from './InputGit'
import {IRepoResponse, RepoResponse} from './RepoResponse'

export interface IInputRepo {
  

  issues : IInputRepoIssues
git : IInputGit

  fetch(/*args*/) : Promise<IRepoResponse>
remove(/*args*/) : Promise<void>
}
  
export const InputRepo = (basePath : string): IInputRepo => {
  return Object.assign(
    
    {
      issues : InputRepoIssues(basePath + '/issues'),
git : InputGit(basePath + '/git'),
fetch(/*args*/) : Promise<IRepoResponse> { return VERBS._fetch<IRepoResponse>(basePath) },
remove(/*args*/) : Promise<void> { return VERBS._remove<void>(basePath) }
    }
  )
}
