
// This file is autogenerated
import * as VERBS from '../verbs'
import {IInputIssueComments, InputIssueComments} from './InputIssueComments'
import {IRepoIssueResponse, RepoIssueResponse} from './RepoIssueResponse'

export interface IInputRepoIssue {
  

  comments : IInputIssueComments

  update(/*args*/) : Promise<IRepoIssueResponse>
fetch(/*args*/) : Promise<IRepoIssueResponse>
remove(/*args*/) : Promise<void>
}
  
export const InputRepoIssue = (basePath : string): IInputRepoIssue => {
  return Object.assign(
    
    {
      comments : InputIssueComments(basePath + '/comments'),
update(/*args*/) : Promise<IRepoIssueResponse> { return VERBS._update<IRepoIssueResponse>(basePath) },
fetch(/*args*/) : Promise<IRepoIssueResponse> { return VERBS._fetch<IRepoIssueResponse>(basePath) },
remove(/*args*/) : Promise<void> { return VERBS._remove<void>(basePath) }
    }
  )
}
