
// This file is autogenerated
import * as VERBS from '../verbs'
import {IInputRepo, InputRepo} from './InputRepo'

export interface IInputRepos {
  (arg1: string, arg2: string): IInputRepo

  

  create(/*args*/) : Promise<IInputRepo>
}
  
export const InputRepos = (basePath : string): IInputRepos => {
  return Object.assign(
    
(arg1: string, arg2: string) => {
  return InputRepo(basePath + '/' + arg1 + '/' + arg2)
},
    
    {
      create(/*args*/) : Promise<IInputRepo> { return VERBS._create<IInputRepo>(basePath) }
    }
  )
}
