
// This file is autogenerated
import * as VERBS from '../verbs'


export interface IIssueCommentResponse {
  

  

  
}
  
export const IssueCommentResponse = (basePath : string): IIssueCommentResponse => {
  return Object.assign(
    
    {
      
    }
  )
}
