
// This file is autogenerated
import * as VERBS from '../verbs'


export interface IRepoIssueResponse {
  

  

  
}
  
export const RepoIssueResponse = (basePath : string): IRepoIssueResponse => {
  return Object.assign(
    
    {
      
    }
  )
}
