
// This file is autogenerated
import * as VERBS from '../verbs'


export interface IRepoResponse {
  

  

  
}
  
export const RepoResponse = (basePath : string): IRepoResponse => {
  return Object.assign(
    
    {
      
    }
  )
}
